# Generated by Django 5.1 on 2024-08-21 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('imageUrl', models.URLField(blank=True, max_length=1024)),
                ('keywords', models.CharField(blank=True, max_length=255)),
                ('types', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('time', models.IntegerField(help_text='Time in minutes')),
                ('servings', models.IntegerField()),
                ('ingredients', models.TextField(help_text='List of ingredients')),
                ('instructions', models.TextField(help_text='Cooking instructions')),
                ('calories', models.IntegerField()),
            ],
        ),
    ]
