# Generated by Django 5.1 on 2024-08-21 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_remove_recipe_imageurl_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='keywords',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='types',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
